- converters/type_conversion.go
- converters/type_conversion_test.go
Here is my naive implementation of DecodeDouble.
This pass all exemples used to have problem.
I hope this helps
> Fix #16 Rewrite of DecodeDouble to limit floating point errors

- .gitignore
- examples/hello_ora/main.go
- network/refuse_packet.go
Company's security rules block direct connection to oracle server when the VPN is on. 
The connect packet is refused, and the actual refused packet is 12 bytes long. This cause a panic in function `newRefusePacketFromData` when trying to get message beyond the 12th byte.
```
panic: runtime error: slice bounds out of range [:383] with capacity 16
goroutine 1 [running]:
github.com/sijms/go-ora/network.newRefusePacketFromData(0xc000012100, 0xc, 0x10, 0xc)
C:/Users/me/go/src/github.com/sijms/go-ora/network/refuse_packet.go:44 +0x165
github.com/sijms/go-ora/network.(*Session).readPacket(0xc0000021e0, 0x0, 0x0, 0x0, 0xfd)
C:/Users/me/go/src/github.com/sijms/go-ora/network/session.go:270 +0x10c
github.com/sijms/go-ora/network.(*Session).Connect(0xc0000021e0, 0xc0000021e0, 0x203000000000000) …
```
> Refused packet makes go_ora panicking

- README.md
- command.go
> Edit README.md: add URL options

- connection.go
A few words on what has been done:
- it's not necessary to read nls_session_parameters 14+ times, we can fetch everything in one query (perhaps even eliminate PL/SQL call then, just execute the SELECT (will do in the next pull request)
- for loop that traversed the stmt.Pars object creates an overhead
- added a check if len(conn.SessionProperties) == 0 before reading elements from it, because it was causing an error when reading from empty SessionProperties array in some rare cases.
> Refactored GetNLS not to issue 14 queries, eliminated slow & unnecessary for loop.

- auth_object.go
- v2/auth_object.go
Docs: https://pkg.go.dev/encoding/hex#DecodeString
> refactor: change function `HexStringToBytes` to Built-in function `hex.DecodeString`

- v2/wallet.go
resovled go version 1.15 don't have os.ReadFile function
> change ReadFile api

- v2/parameter_encode.go
A proposal on how to implement what was discussed in [this issue](https://github.com/sijms/go-ora/issues/177).
Even though I compared the length to the `MAX_LEN_NVARCHAR2` and `MAX_LEN_RAW` variables, I am not sure if those values are always correct, as per what [Oracle documentation says](https://docs.oracle.com/database/121/REFRN/GUID-D424D23B-0933-425F-BC69-9C0E6724693C.htm#REFRN10321). It would probably be safer to just use 4000 or 2000 as the max size for VARCHAR/RAW, respectively, as [CLOBs and BLOBs are automatically mapped](https://docs.oracle.com/cd/B13789_01/server.101/b10759/sql_elements002.htm#:~:text=Oracle%20Database%20automatically%20converts%20a,in%20which%20it%20is%20made.) to VARCHAR or RAW by the database (so it may be safer just to use the lowest possible max size).
> Converts from large strings/bytes into clob/blob

- v2/network/session.go
session read for big blob need multi readPacket
> session read for big blob need multi readPacket

- v2/network/session.go
https://github.com/sijms/go-ora/issues/213
The original PR only fixed this bug in the v1 branch, this ports the fix to v2
> Fixed context and deadline in v2

- examples/structsinsert/main.go
- v2/connection.go
Add StructsInsert support interface array with batch
> Add StructsInsert support interface array with bulk_insert

- v2/data_set.go
- v2/parameter.go
- v2/parameter_encode.go
> fixed bool encode

- examples/issue_333/main.go
The example for the Issue #333
> feat: add example for the reconnection

- .github/workflows/pr.yaml
close #349 
When receiving new PR, do basic code check such as build, format check, test. And also do lint for newly added code.(not for the all code base)
> build: add initial version of ci

- dbms/output.go
- examples/dbms_output/main.go
Hi, DBOutput object adds complexity in large projects because they're forced to add it to their contexts
as a solution it would be easier for them to pass context and we do the job.
and most of mainly used oracle 3rd party apps have a button to enable dbms.out and disable it, so EnableOutput and DisableOutput methods seem to be better choise
> hide DBOutput to decrease complexity

- v2/converters/string_conversion.go
> fix string_conversion bugs for v2 code

- examples/udt_array/main.go
This commit change "ceate"→"create"
> fix: typo miss "create"

- v2/configurations/connect_config.go
- v2/configurations/database_info.go
- v2/connection.go
We are in timezone Europe/Zurich which has an offset of +2h in summer as well as +1h in winter. Unfortunately the database runs in timezone Europe/Zurich as well. 
However the result from Connection#getDBServerTimeZone is not timezone Europe/Zurich but a fixed +2h offset. 
Theoretically the local time of 2024-03-05 10:22:27 should be converted to 2024-03-05 09:22:27 (in winter offset is +1h) but ist converted to 2024-03-05 08:22:27. 
Please let me know if I can help with any further assistance or I am doing something completely wrong. 
Many thanks in advance. 
This MR adds a parameter "SERVER LOCATION" that lets the user configure the Server Timezone explicitly.
> Make Server Timezone Configurable

- network/connect_option.go
- v2/configurations/database_info.go
- v2/configurations/wallet.go
- wallet.go
Fix regular expressions to account for ipv6 in HOST.
> support ipv6

- v2/connection.go
Sorry, to the pool request 
[638](https://github.com/sijms/go-ora/pull/638 ) automatic formatting has been applied. Corrected to the previous format.
> fixed code style

- v2/TestIssues/issue_662_test.go
- v2/command.go
- v2/connection.go
> Support driver.Valuer interface for passed arguments.
