connection.go
I have found the root reason of rejected  connection when my VPN is up.
To do that, I have added trace capability for dumping exchanged packets. I have looked at data exchanged, and noticed that connection string was different whenever I'm connected to the VPN.
So, When the VPN is up, my user is the domain user: `Cassan Jean-Francois (EXTERNAL)`.
When the VPN is down, my user is the local machine user, `jf.cassan` 
And apparently having brackets in user name is not supported. The server refuses the connection without motive, leading to the panic (see  #26).
So I have changed the function `NewConnection` for using UserName instead of  Name.
I'll open another PR for packet dump.
=> Fix user rejected when user's name contains brackets ()

.gitignore, command.go, connection.go, connection_string.go, data_set.go, examples/hello_sql/main.go, network/connect_option.go, network/session.go, trace/trace.go
For going further in debugging, I have found useful to write down exchanged packets into log file. So I have instrumented your code for this purpose.
Let me know your thought about this proposal.
To enable the feature, I have added a parameter on connection string. If this is not appropriate, let me know.
So connection url becomes: 
`oracle://user:pass@server/service_name?TRACE FILE=trace.log`
the trace API is simple:
``` go
type Tracer interface {
Close() error                      // To close file
Print(vs ...interface{})           // like fmt.Print(a,b,c ...)
Printf(f string, s ...interface{}) // like fmt.Printf("%d: %s",1254,"Hello")
LogPacket(s string, p []byte)      // to dump packet like hexdump -C 
IsOn() bool                        // To check if trace is enabled
}
```
For …
=> Add TRACE FILE option

v2/network/oracle_error.go
I encountered this mistake while using the library, just a small spelling mistake fix.
=> Resolved minor spelling mistake in error message.

v2/connection_string.go
or else password with SPACE doesn't work
___
scheme:[//[user:password@]host[:port]]path[?query][#fragment]
before "?" is Path
after "?" is Query
https://www.callicoder.com/golang-url-encoding-decoding/#:~:text=URL%20Encoding%20or%20Escaping%20a%20String%20in%20Go&text=Go%20provides%20the%20following%20two,inside%20a%20URL%20path%20segment.
(but it doesn't matter, because what matters is how oracle implemented it..)
=> PathEscape to encode " " as "%20" instead of "+" (for password)

v2/custom_types.go
To reproduce the solution we need to start with a `Valid = true`
```go
//bad
var expire go_ora.NullTimeStamp
err := db.QueryRow("SELECT SYSTIMESTAMP FROM DUAL").Scan(&expire)
expire_time, err := expire.Value()
log.Info(expire_time)
//  <nil> 
//good!
expire := go_ora.NullTimeStamp{Valid: true}
err := db.QueryRow("SELECT SYSTIMESTAMP FROM DUAL").Scan(&expire)
expire_time, err := expire.Value()
log.Info(expire_time)
// 2022-07-03 07:14:44.351827 +6400 +6400 
```
=> Forgot put `Valid = true` for the custom type `NullTimeStamp` Scan

network/session.go
When using QueryRow or QueryRowContext the context is permanently attached to a new Connection, because Connect is called with the same Context. According to the documentation the Context in Connect should only be used while connecting to the database, not for subsequent queries.
=> Fixed https://github.com/sijms/go-ora/issues/213

v2/connection.go
If first row value of any column has a null value
bulk insert didn't work. The `ORA-24381: error(s) in array DML`
has been returned.
=> fix set data type in bulk insert

v2/command.go, v2/command_test.go
Running queries with leading comments such as `/* foo */` fail because of NewStmt not handling it. This change attempts to help fix that.
Fixes #46.
Note:
* This should be an easy fix with regexp, but I'm guessing you are not doing that for performance reasons. So I just added an `else if` block. Let me know if you want me to change the for loop to a regexp-based fix.
* I also noticed that you did not have ANY dependencies in your go.mod, so I avoided adding a dependency on asserts from `github.com/stretchr/testify/assert` and used simple built-checks in the unit-tests. Let me know if I should change this.
=> NewStmt: ignore all leading comment blocks

v2/parameter_encode.go
Fixed a bug that caused a TTC error when a parameter consisting only of a 0-byte blob was input.
=> Fix blob write bug

v2/connection.go, v2/network/connect_option.go, v2/network/session.go
Allows overriding the default net dialer from the connection options.
I had the need to set a custom dialer to connect to an Oracle DB. I follow the same approach implemented on other drivers like [postgreSQL](https://github.com/lib/pq/blob/v1.10.7/connector.go#L31) and [SQLServer](https://github.com/denisenkom/go-mssqldb/blob/v0.12.3/mssql.go#L181) by adding an option to set a dialer in the OracleConnector and use it in the session instead of the default net dialer.
=> Add dialer in connection options

v2/lob.go
- for go_ora.NClob parameters, lob.read() will not return EOF now.
=> fix: longer lob allowed now. ( > MAX_LEN_VARCHAR2)

v2/data_set.go
I found an issue with the query column types and I made a small change to fix it, It would be great if we could include it in the main repository.
This PR implements the function Length and DecimalSize of sql.ColumnType. Length was partially implemented with some code commented. I implemented it as documented in the `database/sql` package.
I used this test to validate the changes. Happy to add it to the `go_ora` package too, if it can be useful, but it's an integration test requiring a DB connection.
``` go
package main
import (
"database/sql"
"testing"
_ "github.com/sijms/go-ora/v2"
)
const dns = "oracle://system:password@localhost:1521/XE"
func TestColumnLenPrecScale(t *testing.T) {
for _, tt := range []struct {
testName         string
query            string
expDBType        string …
```
=> Implements the functions Length and DecimalSize of sql.ColumnType

connection.go, v2/connection.go
Error:ORA-06550: line 21, column 4:
PL/SQL: ORA-00980: synonym translation is no longer valid
ORA-06550: line 3, column 3:
PL/SQL: SQL Statement ignored
=> When there is an issue with the user's permissions, it can cause an error to be reported

v2/network/session.go
This prevents certificate errors when trying to connect via TLS without a wallet.
Options that worked for me:
```
import (
go_ora "github.com/sijms/go-ora/v2"
oracle "github.com/godoes/gorm-oracle" // Only needed for GORM
"gorm.io/gorm" // Only needed for GORM
)
urlOptions := map[string]string{
//"TRACE FILE": "trace.log",
"AUTH TYPE":  "TCPS",
"SSL":        "TRUE",
"SSL VERIFY": "TRUE",
}
```
Then I used JDBC string since "connStr" was the only  this I was sure was correct.
```
jdbc := "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=" + ORACLE_SERVER + "))(connect_data=(service_name=" + ORACLE_SERVICE + "))(security=(ssl_server_dn_match=yes)))"
cleanJDBC := go_ora.BuildJDBC( ORACLE_USER ,  ORACLE_PASS), jdbc, urlOptions)
```
Using normal go-ora:
``` …
```
=> Allow for tls connection without certificate (one-way TLS)

v2/connection_string.go
when updating from 2.6.9, i received error `starting from v2.7.0 this feature is not supported and the driver use database/sql package fail over` and found out that it's in the connection string. By clearing the error message i hope future people can trace the error quickly. Thank you
=> improve failover and retry time err message

v2/connection_string.go
An additional nil check for `q` before the loop is unnecessary because `q` is a `map`. A nil `map` is equivalent to an empty map. (Example: https://go.dev/play/p/EnnDEF7svOd)
Before:
```go
if q != nil {
for key, val := range q {
...
}
}
```
After:
```go
for key, val := range q {
...
}
```
=> connection_string: remove redundant nil check

v2/network/oracle_error.go
Error occurs on high load of Oracle database. 
e.g http://www.dba-oracle.com/t_ora_12516-tns_ould_not_find_available_handler.htm
=> add error message for ORA-12516

v2/network/session.go
This change increases the amount of space that is reserved for Native Network Encrpytion checksums and encryption overhead. Without this change, clients sending large buffers to the server can experience arbitrary disconnections since the resulting data packet may exceed the SessionDataUnit size.
This change has been spot-checked with Oracle Database 19c and 21c with the following lines in the `sqlnet.ora` file:
```
SQLNET.ENCRYPTION_SERVER = REQUIRED
SQLNET.ENCRYPTION_TYPES_SERVER = AES256
SQLNET.ENCRYPTION_CLIENT = REQUIRED
SQLNET.ENCRYPTION_TYPES_CLIENT = AES256
SQLNET.CRYPTO_CHECKSUM_SERVER = REQUIRED
SQLNET.CRYPTO_CHECKSUM_TYPES_SERVER = SHA256
SQLNET.CRYPTO_CHECKSUM_TYPES_CLIENT = SHA256
SQLNET.CRYPTO_CHECKSUM_CLIENT  = REQUIRED
SQLNET.EXPIRE_TIME = 10
```
Fixes #444
=> go-ora/v2/network: Reserve additional packet space for NNE

v2/command.go, v2/connection.go, v2/network/oracle_error.go, v2/ref_cursor.go, v2/simple_object.go, v2/utils.go
Fixes #455 
This set of changes primarily does 3 things:
1. Changes the "bad" connection indicator to be something that can be atomically managed.
2. Sets the connection to be "bad" in every place that isBadConn(err) says that the connection is bad.
3. Augments the OracleError type to have a Bad() method so that oracle error codes indicating that the connection is invalid are stored in one place.
=> Augment bad connection management

.gitignore, v2/module_test/go.mod, v2/module_test/int_test.go, v2/module_test/money_test.go, v2/module_test/real_test.go, v2/module_test/sql_test.go
- Tests are organized in their own package under directory `v2/module_test/`.
- Tests added in this PR: tests for integers, real numbers and money data types.
Start an Oracle instance locally with Docker:
```sh
$ docker run --restart unless-stopped -d --name oracle-xe -p 1521:1521 -e ORACLE_PWD=SecretPassword1 container-registry.oracle.com/database/express:21.3.0-xe
```
Run tests:
```sh
$ export ORACLE_DSN="oracle://system:SecretPassword1@localhost:1521/?SID=XE"
$ cd v2/module_test
$ go test -v -count 1 -p 1 ./
```
P/S: if a value stored in a floating point column (e.g. `NUMERIC(x,y)`) have zero fraction part (e.g. `123.00`) then it is fetched as an integer (e.g. Go's `int/uint`).
I consider this is a bug because the fetched value should be in Go's `float32/float64`. Hence some tests …
=> Added tests

v2/driver.go
If  `go_ora.AddSessionParam(db, "CURRENT_SCHEMA", schema)` used, single quotes at `"alter session set %s='%s'"` raises ORA-02421: missing or invalid schema authorization identifier.
I think the caller should do escaping (add quotes) if necessary.
```
go_ora.AddSessionParam(db, "CURRENT_SCHEMA", schema)
go_ora.AddSessionParam(db, "nls_date_format", "'DD-MON-YYYY HH24:MI:SS'")
```
=> fix alter session set_clause

v2/connection_string.go
1 - cross-platform cutting the last segment from `os.Args[0]` with `path/filepath`
2 - PROGRAM option to set value via connect string
=> Minor bugfix ProgramName on Windows + override option

v2/parameter.go
A small followup to fix https://github.com/sijms/go-ora/issues/546
=> Fix local timezone

v2/utils.go
Fixed: utils.refineSqlText - Removed the increment from the form index if the character is '\\', as it is removing a single quote when the query has a concatenation of texts with a slash, leaving the skip equal to true for the rest of the query.
The error caused when the query has parameters.
Example: SELECT ID, DESCRIPTION||'\'||DESCRIPTION FROM FAB_PROCESSO WHERE ID = :ID
Error: ORA-01008: not all variables bound
=> Fixed: utils.refineSqlText - Removed the increment from the form index

v2/connection.go, v2/data_set.go
During usage, we encountered a Panic error:
```
error: interface conversion: driver.Rows is nil, not *go_ora.DataSet
runtime.panicdottypeE
/usr/local/go/src/runtime/iface.go:262
runtime.panicdottypeI
/usr/local/go/src/runtime/iface.go:272
github.com/sijms/go-ora/v2.(*Connection).QueryRowContext
/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/connection.go:1083
github.com/sijms/go-ora/v2.(*Connection).getDBTimeZone
/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/connection.go:509
github.com/sijms/go-ora/v2.(*Connection).dataTypeNegotiation
/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.19/connection.go:1289
```
After investigation, it seems that the issue was caused by not handling the error in the code. 
Therefore, submitted this PR to resolve the problem and also fixed #564
=> Fix problem caused by not handling error

v2/configurations/database_info.go, v2/connection.go
I needed ability to use SYSDG role to monitor database in MOUNTED state using https://github.com/iamseth/oracledb_exporter.
I'm not advanced Golang programmer - but this simple change works for me and does not break ability to connect to older versions (tested this with 11gR2 which does not support SYSDB privilege and with 12.x, 18.x and 19.x - which works in such mode)
=> Add authentication for SYSDG and other roles

v2/number.go
in my testing oracle I have number column and extra large numbers
```
ID_OP      PRICE      OASUM
---------- ---------- ----------
37840227          ~         -~
```
I found answer in docs.
https://docs.oracle.com/cd/B13789_01/server.101/b10759/sql_elements004.htm
```
If a positive NUMBER value is extremely large and cannot be represented in the specified format, 
then the infinity sign (~) replaces the value. 
Likewise, if a negative NUMBER value is extremely small and 
cannot be represented by the specified format, then the negative infinity sign replaces the value (-~).
```
https://github.com/sijms/go-ora/issues/579 related issue
=> inf in number type

v2/configurations/database_info.go, v2/connection.go
#563 added support for SYSDG and other Oracle administrative privileges.  These changes got inadvertently clobbered by #591.  This PR brings them back, in addition to correcting privileges SYSBACKUP, SYSDG, and SYSKM to match their string names rather than the oci.h abbreviations.  So we recognize `/ AS SYSBACKUP` to match https://docs.oracle.com/en/database/oracle/oracle-database/19/dbseg/configuring-privilege-and-role-authorization.html, rather than `/ AS SYSBKP`.
=> Restore SYSDG and other administrative privileges

v2/number.go
In some cases exp value is not 0 which leads to incorrect decoding.
=> Fix decode Infinity number. Exp value always must be 0.

examples/mtls/main.go, v2/configurations/session_info.go, v2/connection.go, v2/network/session.go
Add `WithTLSConfig` method to `OracleConnector` for injecting custom *tls.Config`. This allows easy programmatic control over TLS negotiation. Also, include an example demonstrating its usage.
=> Add `WithTLSConfig` method to `OracleConnector`

v2/converters/other_types.go
Fixes: #603
Fixes the following problem when compiling for 32bit arch
```
Building linux/386
/Users/ilyam/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.21/converters/other_types.go:81:25: 2147483648 (untyped int constant) overflows int
/Users/ilyam/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.21/converters/other_types.go:102:23: 2147483648 (untyped int constant) overflows int
/Users/ilyam/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.21/converters/other_types.go:108:21: 2147483648 (untyped int constant) overflows int
/Users/ilyam/go/pkg/mod/github.com/sijms/go-ora/v2@v2.8.21/converters/other_types.go:116:21: 2147483648 (untyped int constant) overflows int
```
=> fix "overflows int" on 32bit arch

v2/converters/other_types_test.go
The test `github.com/sijms/go-ora/v2/converters/generatefloat` is failing for me:
```
~/git/static/go-ora/v2/converters$ go clean -testcache && go test
--- FAIL: TestBinaryFloat (0.00s)
other_types_test.go:32: expected -134.45, got -134.44
FAIL
exit status 1
FAIL	github.com/sijms/go-ora/v2/converters	0.033s
```
This change updates the expected value, causing the test to succeed:
```
~/git/static/go-ora/v2/converters$ go clean -testcache && go test
PASS
ok  	github.com/sijms/go-ora/v2/converters	0.033s
```
=> Fix failing unit test in other_types_test.go

examples/kerberos/main.go
The `PR Check` GitHub Action runs `go fmt` and then builds and unit tests.  But the `go fmt` run is currently failing with the error message:
```
package github.com/sijms/go-ora/examples/kerberos: C++ source files not allowed when not using cgo or SWIG: kerberos.cpp
```
This change adds a dummy cgo dependency in the example to make this error go away and unblock the PR checks.  The PR checks will continue failing for now, however, because some unit tests themselves are failing.
=> Add cgo dependency to avoid go fmt failures

network/oracle_error.go, network/session.go, v2/network/oracle_error.go, v2/network/session.go
Add ErrPos() interface to OracleError, which makes it easier for users to be informed of the specific location where the error occurred.
=> Add ErrPos() interface to OracleError

v2/number.go
In the decode() function for the NUMBER data type, there is no array size check, which leads to array overruns and panic at decoding some incorrectly generated values in the database:
```
panic: runtime error: index out of range [-1]
goroutine 25 [running]:
github.com/sijms/go-ora/v2.(*Number).decode(0x0?)
/.../github.com/sijms/go-ora/v2/number.go:188 +0x27f
```
=> Fix panic at number decoding

v2/connection.go
Currently, the code tries to do a type assertion before verifying no error was returned from `QueryContext`, additionally, it is not verifying the type assertion worked properly. 
This PR adds correct error and type assertion handling to the `QueryRowContext` function.
=> Handle type assertion correctly

examples/kerberos/main.go, v2/advanced_nego/advanced_nego.go, v2/configurations/connect_config.go, v2/connection.go
This PR makes it possible to have different Kerberos auth objects for different connections. If the session-specific auth is present, it is preferred to the global object.
The example program is updated to make it functional and showcase both modes.
=> Implement per-session Kerberos auth settings. Update Kerberos example.

v2/connection.go
With an invalid DSN, I got a panic with such a backtrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xbc2ba8]
goroutine 88 [running]:
github.com/sijms/go-ora/v2.(*OracleDriver).Open(0x1dc91a0, {0xc0000c22c0, 0x39})
vendor/github.com/sijms/go-ora/v2/connection.go:178 +0xc8
github.com/simukti/sqldb-logger.(*connector).Connect(0xc0001941e0, {0xe788d8, 0x1e12c80})
vendor/github.com/simukti/sqldb-logger/connector.go:21 +0x1a3
database/sql.(*DB).conn(0xc0001901a0, {0xe788d8, 0x1e12c80}, 0x1)
...
```
=> fixed panic due to incorrect dsn

v2/converters/other_types.go, v2/converters/other_types_test.go
There is bug in formula for negative date interval year to month. It doesn't work for any value other then 10 month and it contradicts comment which states the value is "month + 60"
I've made changes to align code with date to seconds version and added test.
Also fixed case when interval is negative but year or day is zero.
=> Fix negative interval for year to month

v2/converters/other_types.go, v2/converters/other_types_test.go
Go-ora types support is very wide and convenient, but i noticed that current implementation of `ConvertBinaryFloat`  leads to loss of accuracy. Please check [ConvertBinaryFloat test](https://github.com/sijms/go-ora/blob/576a11c0240aeeacf72d87dff66c4e4d3cde55d7/v2/converters/other_types_test.go#L21):
- Input: `134.45`
- Expected output: `134.44`
In given case [math.Trunc](https://github.com/sijms/go-ora/blob/576a11c0240aeeacf72d87dff66c4e4d3cde55d7/v2/converters/other_types.go#L44) cuts most of the fractional part (134.44**999** <- these last numbers), which leads to loss of accuracy.
Step by step transformation:
- Return float32, so user can use correct value. Oracle `BINARY_FLOAT` is 32-bit floating-point number, so Golang float32 is the closest type
- User still can cast to float64 on …
=> fix: return go float32 for oracle BINARY_FLOAT type

v2/connection.go
[This change](https://github.com/sijms/go-ora/commit/487451c9af0085729c95fcfb7a77932d8a3b3ef9#diff-14ca2675a55cb4d69070e5d02bbae246339ffeb8343e8a966f78d5542c18700cL288) to the `Connection.getStrConv` function in v2.8.21 caused a regression in my application.  This PR fixes that regression by restoring that function's previous logic.
Context: My application specifies `CLIENT CHARSET=UTF8` in order to send and receive UTF-8 characters to and from a US7ASCII database.  When my application calls stored procedures that use the HTP package to generate an HTTP response and then OWA.GET_PAGE to return that response, the regression causes non-ASCII UTF-8 characters to be converted to `?` characters.
(I don't actually know what the difference is between `cStrConv`, `sStrConv`, and `nStrConv`, so …
=> Fix character set regression

v2/utils.go
Hi, found bug when tried to execute query with qoueted string, which contains http link.
like that: "select '"http://something"' from dual" (note single and double qoutes).
function refineSqlText which used by parseQueryParametersNames ignores order of quotation.
refineSqlText returns "select http:something from dual" and ":something" populates named parameters array.
This PR fixes that.
=> fix query parameters incorrect parsing

v2/network/session.go
This functionality has already been added in the v1 session code, but it is missing in v2
=> fix: when compress is true the size may be greater than 8

v2/configurations/database_info.go
I had a interesting bug.
In the following connection string only the second address was successful parsed by the current regex. From my understanding, the fist one is also valid, which is why I changed the regex to include more whitespaces in the regex. Then it would parse both addresses successfully.
```
(DESCRIPTION = 
(ADDRESS_LIST = 
(ADDRESS = (PROTOCOL = TCP) (HOST = DB1) (PORT = 1521) )
(ADDRESS = (PROTOCOL = TCP)(HOST = DB2)(PORT = 1521))
)
)
```
=> ServerAddr can have spaces between the informations

v2/command.go
This PR fixes an issue where using bind variables (inside statement) in a different case than their corresponding parameters in the parameter list results in the error "parameter %s is not defined in parameter list".
Problem:
When binding parameters, the comparison between bind variable names and parameter names was case-sensitive, causing failures when the cases didn't match exactly.
Solution:
Modified the parameter name comparison to be case-insensitive, ensuring consistent behavior regardless of the case used in bind variables.
=> case-insensitive parameters matching
